### PR TITLE
Add "userinfo" command and few fixes.

### PR DESCRIPTION
**Pull request by WopsS**
Not completed yet, it contains basic things.

### CODE REVIEW

**Comment by JohnyMac** [comment]
OK.. u are faster then me lol.. just a tip: 
You could use xpath itself to get the link of thread, like xpath that should get the href attribute: 
`td[class="alt1"]/div[class="alt2"]/div/em/a/@href`

Also, you could get threads only by user so that way you don't need to search for his post cause it's always first.
http://forum.sa-mp.com/search.php?do=finduser&u=ID_HERE&starteronly=1

**Comment by WopsS** [comment]
Thanks for the tip @JohnyMac! A user can have reputation if doesn't post a new topic. Anyway, it is the same if we get his threads or his posts.

**Comment by Southclaws** [comment]
The line endings is causing oddities in the diff: https://github.com/Southclaws/cj/pull/19/files

**Comment by WopsS** [comment]
I changed them to LF in 4afcf2780bb1c7a7349d3f3ec79e4a97b4b4334c.

**Comment by WopsS** [comment]
I rechecked the files and I see CRLF, I don't know why VS Code showed me it use LF first time.

**Comment by WopsS** [comment]
I rechecked the files and line ending is CRLF, it is good because git didn't listen to me in that commit. Git changed it from LF to CRLF.

**Pull request closed without merging**
