### PR TITLE
Add OpenMP, Burger, and Google memes

### PR DESCRIPTION
**Pull request by Gigabitzz**

### CODE REVIEW

**Comment by Southclaws** [comment]
the real mvp PRs 🙏

**Comment by Southclaws** [comment]
`bot/commands/cmd_gmname.go:72:19: syntax error: unexpected newline, expecting comma or }`

**Comment by BigETI** [comment]
wtf OpenMP is not open.mp

**Comment by Gigabitzz** [comment]
Fixed.

**Pull request merged**
