### PR TITLE
cmd wiki improvement

### PR DESCRIPTION
**Pull request by DAKYSKYE**

### CODE REVIEW

**Comment by DAKYSKYE** [comment]
So now it doesn't matters if you search case-sensitive or case-insensitive, you're getting variations of what you may be searching for (note: levenshtein distance = 3). also, it "auto-corrects" if you mistype a char or two, like if you search onpla*u*erconnect by accident, it will still search for `OnPlayerConnect`

**Comment by DAKYSKYE** [comment]
and also ! I'm sure I've made signed commits ;-;

**Comment by DAKYSKYE** [comment]
Let me fix everything, I'll make pr again and try to sign commits (I'm sure I've used `-S` while commiting but..)

**Comment by DAKYSKYE** [comment]
P.s 
image

**Comment by DAKYSKYE** [comment]
Travis CI may be failing because I'm stick with go 1.12

**Comment by DAKYSKYE** [comment]
I don't know what to do now..

**Comment by DAKYSKYE** [comment]
Hope moving json to go array would pass travis' build check!

**Comment by DAKYSKYE** [comment]
Yes, finally !

**Comment by Southclaws** [comment]
Thanks for you contribution! 👍

**Pull request merged**
