### PR TITLE
Helper

### PR DESCRIPTION
**Pull request by dakyskye**
image

I implemented #32 

How it works:
1) checks if a sent message is in the scripting channel
2) checks if the assistance cooldown is expired or not since the last assistance
3) checks if the message content contains a [sub-string](https://github.com/dakyskye/cj/blob/helper/bot/discord.go#L27). If it contains but assistance cooldown isn't expired, it adds a question mark reaction to the message
4) find the helper role
5) finds the online guild members with that role
6) if helpers are online, the list of them is posted, otherwise a message with note that the question __may__ be unanswered and sets cooldown again

### CODE REVIEW

**Comment by Southclaws** [comment]
Looks great, code is fine! However, it's currently in the main event dispatch rather than its own part of the code.

I wrote a simple "extension" system where you can register callbacks, so this should go in an extension instead. Check out the way that other extensions are built and registered here: https://github.com/Southclaws/cj/blob/master/bot/core.go#L73-L76

Basically you just need to satisfy the `Extension` interface.

**Comment by dakyskye** [comment]
Ah, I see. I'll make it an extension.

**Comment by dakyskye** [comment]
Found out discordgo has a bug, it duplicates members whilst iterating over `Guild.Member`, so I added an extra check for it.

**Comment by dakyskye** [comment]
Oh, thanks. Good to hear.

**Pull request merged**
